### ISSUE TITLE
Update rWCVPdata

### ISSUE THREAD

**Issue by xueqinerer** [matildabrown/rWCVPdata#5]
Hi,
How can rWCVP use the latest version of WCVP database? How can I use the downloaded WCVP database instead of the original rWCVPdata?Thank you very much.

**Comment by matildabrown** [comment]
Hi! For v13 of the WCVP, rWCVPdata has been updated, so updating the package will give you the current data: 
`devtools::install_github("matildabrown/rWCVPdata")`

To use a specific version of the WCVP, you can provide a local copy of the data to `rWCVP` - see https://github.com/matildabrown/rWCVP/issues/61 for more details. 

Hope this helps, feel free to reopen if not. 

Cheers, 
Matilda

**Comment by xueqinerer** [comment]
Hi,
I have used this code, but citation("rWCVPdata ") shows the last version, so I am not sure whether to install the latest version, thank you.
![微信图片_20240604083557](https://github.com/matildabrown/rWCVPdata/assets/165108001/16fbbab2-51fa-4bd4-9708-31f567c431c3)

**Comment by matildabrown** [comment]
Ah, thanks for finding this bug! The citation file wasn't updating properly. It should be working now! There's also `wcvp_version()` which shouldn't have the bug.

**Comment by xueqinerer** [comment]
Thank you very much.
